"""Type stubs for the compiled ``anqa._core`` module."""

def keep_updates_line(line: bytes) -> bool: ...
def filter_updates(data: bytes) -> list[bytes]: ...
def find_sessions(root: str) -> list[str]: ...
def looks_like_session_dir(path: str) -> bool: ...
def find_files(root: str, suffix: str, name_prefix: str) -> list[str]: ...
def store_ids() -> list[str]: ...
def store_discover(harness: str, roots: list[str]) -> list[dict[str, str]]: ...
def store_list_meta(harness: str, locator: str, session_id: str) -> dict[str, object]: ...
def store_detail_meta(harness: str, locator: str, session_id: str) -> dict[str, object]: ...
def store_timeline(harness: str, locator: str, session_id: str) -> list[dict[str, object]]: ...
def store_timeline_page(
    harness: str, locator: str, session_id: str, offset: int, limit: int
) -> dict[str, object]: ...
def store_stamp(harness: str, locator: str, session_id: str) -> tuple[float, int, int, int]: ...
def store_overview(harness: str, locator: str, session_id: str) -> dict[str, object]: ...
